// Generated by web/generate.py from TypeMeIt/Overlay/Puff.metal. Do not edit.
const PUFF_GLSL = String.raw`
// Generated by web/generate.py from TypeMeIt/Overlay/Puff.metal. Do not edit.
float saturate(float x) { return clamp(x, 0.0, 1.0); }
// Overall puff radius for an expansion value, in view units where the short
// side spans -0.5...0.5.
float radius(float e) { return mix(0.05, 0.25, e); }

vec3 mod289(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
vec4 mod289(vec4 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
vec4 permute(vec4 x) { return mod289(((x * 34.0) + 1.0) * x); }
vec4 taylorInvSqrt(vec4 r) { return 1.79284291400159 - 0.85373472095314 * r; }

// Simplex noise (Gustavson / McEwan), range roughly -1...1.
float snoise(vec3 v) {
    const vec2 C = vec2(1.0 / 6.0, 1.0 / 3.0);
    const vec4 D = vec4(0.0, 0.5, 1.0, 2.0);

    vec3 i = floor(v + dot(v, C.yyy));
    vec3 x0 = v - i + dot(i, C.xxx);

    vec3 g = step(x0.yzx, x0.xyz);
    vec3 l = 1.0 - g;
    vec3 i1 = min(g.xyz, l.zxy);
    vec3 i2 = max(g.xyz, l.zxy);

    vec3 x1 = x0 - i1 + C.xxx;
    vec3 x2 = x0 - i2 + C.yyy;
    vec3 x3 = x0 - D.yyy;

    i = mod289(i);
    vec4 p = permute(permute(permute(
        i.z + vec4(0.0, i1.z, i2.z, 1.0))
        + i.y + vec4(0.0, i1.y, i2.y, 1.0))
        + i.x + vec4(0.0, i1.x, i2.x, 1.0));

    float n_ = 0.142857142857;
    vec3 ns = n_ * D.wyz - D.xzx;

    vec4 j = p - 49.0 * floor(p * ns.z * ns.z);
    vec4 x_ = floor(j * ns.z);
    vec4 y_ = floor(j - 7.0 * x_);

    vec4 x = x_ * ns.x + ns.yyyy;
    vec4 y = y_ * ns.x + ns.yyyy;
    vec4 h = 1.0 - abs(x) - abs(y);

    vec4 b0 = vec4(x.xy, y.xy);
    vec4 b1 = vec4(x.zw, y.zw);

    vec4 s0 = floor(b0) * 2.0 + 1.0;
    vec4 s1 = floor(b1) * 2.0 + 1.0;
    vec4 sh = -step(h, vec4(0.0));

    vec4 a0 = b0.xzyw + s0.xzyw * sh.xxyy;
    vec4 a1 = b1.xzyw + s1.xzyw * sh.zzww;

    vec3 p0 = vec3(a0.xy, h.x);
    vec3 p1 = vec3(a0.zw, h.y);
    vec3 p2 = vec3(a1.xy, h.z);
    vec3 p3 = vec3(a1.zw, h.w);

    vec4 norm = taylorInvSqrt(vec4(dot(p0, p0), dot(p1, p1), dot(p2, p2), dot(p3, p3)));
    p0 *= norm.x; p1 *= norm.y; p2 *= norm.z; p3 *= norm.w;

    vec4 m = max(0.6 - vec4(dot(x0, x0), dot(x1, x1), dot(x2, x2), dot(x3, x3)), 0.0);
    m = m * m;
    return 42.0 * dot(m * m, vec4(dot(p0, x0), dot(p1, x1), dot(p2, x2), dot(p3, x3)));
}

// Five octaves, the xy plane rotated between octaves so no lattice direction
// survives into the result. Range roughly -1...1.
float fbm(vec3 p) {
    const mat2 rot = mat2(0.80, 0.60, -0.60, 0.80);
    float sum = 0.0;
    float amp = 0.5;
    float norm = 0.0;
    for (int i = 0; i < 5; i++) {
        sum += amp * snoise(p);
        norm += amp;
        p = vec3(rot * p.xy * 2.03, p.z * 1.7 + 11.3);
        amp *= 0.5;
    }
    return sum / norm;
}

// Coarse shape of the puff: a soft core with a ring of six lobes around it,
// each swelling and drifting on its own slow cycle, plus one low octave of
// noise so the lobes are not perfect spheres. This is what gets lit. Time is
// only ever an oscillator phase or the third noise axis, so nothing drifts
// unbounded. 'uv' is centred and normalised so the view's short side spans
// -0.5...0.5.
float shape(vec2 uv, float time, float e) {
    // The lobed mass sits well inside the puff's overall radius; the thin haze
    // added in 'field' carries the fade out to the full extent.
    float R = radius(e) * 0.68;

    float mass = 0.85 * exp(-dot(uv, uv) / (R * R * 0.32));

    float spin = time * 0.045;
    for (int i = 0; i < 6; i++) {
        float k = float(i);
        float ang = spin + k * 1.0472 + 0.30 * sin(time * 0.31 + k * 1.7);
        float reach = R * (0.58 + 0.12 * sin(time * 0.43 + k * 2.3));
        vec2 c = reach * vec2(cos(ang), sin(ang));
        float r = R * (0.42 + 0.08 * sin(time * 0.37 + k * 0.9));
        vec2 q = uv - c;
        mass += exp(-dot(q, q) / (r * r * 0.40));
    }

    float low = snoise(vec3(uv * (1.6 / R), time * 0.12));
    return mass * (0.82 + 0.22 * low);
}

// Advected fractal noise, 0...1. Features ride outwards from the centre as
// 'flow' increases and back in as it decreases: the domain is zoomed by the
// fractional part of 'flow', and two layers float a cycle apart are cross-faded
// so each one resets while its weight is zero. Nothing ever leaves float
// range, however long the app runs.
float flowNoise(vec2 uv, float flow, float time, float R) {
    float n = 0.0;
    float wsq = 0.0;
    for (int layer = 0; layer < 2; layer++) {
        float ph = flow + 0.5 * float(layer);
        float fi = fract(ph);
        float w = 1.0 - abs(2.0 * fi - 1.0);
        float zoom = exp2(-fi);
        float z = floor(ph) * 17.3 + float(layer) * 31.7;
        vec2 p = uv * (2.75 / R) * zoom;
        vec2 warp = vec2(
            fbm(vec3(p * 0.5, z + time * 0.08)),
            fbm(vec3(p * 0.5 + vec2(5.2, 1.3), z + 7.0 + time * 0.08)));
        n += w * fbm(vec3(p + 0.9 * warp, z + 3.1 + time * 0.12));
        wsq += w * w;
    }
    // Blending two independent fields lowers the variance mid-fade; dividing
    // by the weight norm keeps the contrast constant through the cycle.
    n /= sqrt(wsq);
    return smoothstep(-0.55, 0.6, n);
}

// Same two-layer advection for the fine grain.
float flowGrain(vec2 uv, float flow, float time, float R) {
    float g = 0.0;
    float wsq = 0.0;
    for (int layer = 0; layer < 2; layer++) {
        float ph = flow + 0.5 * float(layer);
        float fi = fract(ph);
        float w = 1.0 - abs(2.0 * fi - 1.0);
        g += w * snoise(vec3(uv * (6.5 / R) * exp2(-fi), floor(ph) * 5.1 + float(layer) * 9.7 + time * 0.2));
        wsq += w * w;
    }
    return 0.5 + 0.5 * g / sqrt(wsq);
}

// Smoke density of the body, 0...~1.4: the shape carved by the advected
// noise 'n', then thinned with distance from the centre so the rim is
// translucent wisps.
float field(vec2 uv, float time, float e, float n) {
    float R = radius(e);
    float d2 = dot(uv, uv) / (R * R);
    // Dense lobed core plus a wide, thin haze that reaches the full radius.
    float mass = shape(uv, time, e) + 0.42 * exp(-1.1 * d2);

    // Noise bites hardest where the mass is thin, so the rim is carved into
    // wisps while the centre stays solid.
    float thin = 1.0 - saturate(mass);
    float density = mass * (1.0 - (0.38 + 0.55 * thin) * (1.0 - n));

    // Radial falloff: dense middle, thin edge.
    density *= exp(-1.1 * d2);

    return max(0.0, density - 0.12);
}

// Fragments left behind when the puff retracts: the body's own density as it
// was at the size it is retreating from ('trail'), kept only outside the
// current body, and only where a slow low-frequency mask and the densest
// clumps of the advected noise coincide. So they are bits of the larger
// cloud left inside its old footprint, and they fade as the trail catches up.
float orphans(vec2 uv, float time, float e, float trail, float n) {
    float gap = trail - e;
    if (gap <= 0.005) { return 0.0; }
    float Re = radius(e);
    float d = length(uv);
    float was = field(uv, time, trail, n);
    float outside = smoothstep(Re * 1.05, Re * 1.5, d);
    float mask = smoothstep(0.6, 0.88, 0.5 + 0.5 * snoise(vec3(uv * (1.1 / radius(0.5)) + 7.0, time * 0.06)));
    float clumps = n * n * n;
    return 0.6 * was * outside * mask * clumps * saturate(gap * 4.0);
}

// Fixed amount of smoke: opacity falls with the area it is spread over, so
// the small puff is dense and the expanded one is the same smoke spread thin.
float conserve(float e) {
    return clamp(pow(radius(0.35) / radius(e), 2.0), 0.12, 3.0);
}

// Colour of the puff at 'position' in a view of 'size', premultiplied.
// expansion: 0 = fully retracted wisp, 1 = fully expanded cloud.
// trail: the expansion the puff is retreating from, >= expansion. Fragments
//        are left in the shell between the two; equal means none.
// flow: outward drift phase; one unit doubles the distance of every feature.
//       Increase it to stream smoke outwards, hold it to let it hang.
// tint: colour of the smoke; alpha scales overall opacity.
vec4 render(vec2 position, vec2 size, float time, float expansion, float trail, float flow, vec4 tint) {
    float scale = min(size.x, size.y);
    vec2 uv = (position - 0.5 * size) / scale;
    float e = saturate(expansion);
    float tr = max(e, saturate(trail));

    // Beyond 1.6 radii the density floor has removed everything, so skip the
    // noise there; most of the view is this cheap.
    if (dot(uv, uv) > 2.56 * radius(tr) * radius(tr)) { return vec4(0.0); }

    // The noise is scaled by a fixed mid radius, not the current one, so a
    // change of size moves smoke through the field instead of zooming it.
    float n = flowNoise(uv, flow, time, radius(0.5));
    float body = field(uv, time, e, n);
    float left = orphans(uv, time, e, tr, n);
    float f = body + left;
    if (f <= 0.0) { return vec4(0.0); }

    // Light the coarse shape from the upper left: each lobe gets a bright
    // top and a shadowed underside, and the fine carving stays unlit so it
    // reads as vapour rather than rock.
    float R = radius(e) * 0.68;
    float h = R * 0.12;
    float s0 = shape(uv, time, e);
    vec2 grad = vec2(shape(uv + vec2(h, 0.0), time, e) - s0,
                         shape(uv + vec2(0.0, h), time, e) - s0) / h;
    vec2 light = normalize(vec2(-0.4, -1.0));
    float lit = saturate(0.5 - 0.13 * R * dot(grad, light));

    // Fine grain, one high octave at low weight, drifting with the flow.
    float grain = flowGrain(uv, flow, time, radius(0.5));

    // Beer-Lambert style opacity: dense centre, soft translucent edges. The
    // body is as thin as its own size demands; the fragments as thin as the
    // size they were shed from.
    float alpha = 1.0 - exp(-1.9 * (conserve(e) * body + conserve(tr) * left));
    // A white or grey tint takes deep shadows; a coloured one is shaded
    // only lightly, since darkening a hue towards black reads as soot.
    float peak = max(tint.r, max(tint.g, tint.b));
    float saturation = peak > 0.0 ? (peak - min(tint.r, min(tint.g, tint.b))) / peak : 0.0;
    float floor_ = mix(0.64, 0.86, saturation);
    float shade = mix(floor_, 1.0, lit) * mix(mix(0.88, 0.96, saturation), 1.0, saturate(f)) * (0.96 + 0.06 * grain);

    float a = float(alpha) * tint.a;
    return vec4(tint.rgb * float(shade) * a, a);
}
`;
